name: 🧪 E2E - workflow a
on:
  repository_dispatch:
    types: [workflow-a-tests]
jobs:
  a-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          spec: cypress/e2e/a-tests/*.cy.js